<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-5IC372P" name="Default test" tests="18" failures="1" timestamp="7 Apr 2017 02:28:51 GMT" time="0.214" errors="0">
  <testcase name="test1" time="0.01" classname="com.selenium.testNG.Demo"/>
  <testcase name="test2" time="0.003" classname="com.selenium.testNG.Demo">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at com.selenium.testNG.Demo.test2(Demo.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="a" time="0.002" classname="com.selenium.testNG.FactoryExample"/>
  <testcase name="a" time="0.002" classname="com.selenium.testNG.FactoryExample"/>
  <testcase name="a" time="0.003" classname="com.selenium.testNG.FactoryExample"/>
  <testcase name="a" time="0.003" classname="com.selenium.testNG.FactoryExample"/>
  <testcase name="a0" time="0.003" classname="com.selenium.testNG.FactoryExample"/>
  <testcase name="a0" time="0.004" classname="com.selenium.testNG.FactoryExample"/>
  <testcase name="a0" time="0.004" classname="com.selenium.testNG.FactoryExample"/>
  <testcase name="a0" time="0.005" classname="com.selenium.testNG.FactoryExample"/>
  <testcase name="b" time="0.002" classname="com.selenium.testNG.FactoryExample"/>
  <testcase name="b" time="0.006" classname="com.selenium.testNG.FactoryExample"/>
  <testcase name="b" time="0.002" classname="com.selenium.testNG.FactoryExample"/>
  <testcase name="b" time="0.003" classname="com.selenium.testNG.FactoryExample"/>
  <testcase name="c" time="0.005" classname="com.selenium.testNG.FactoryExample"/>
  <testcase name="c" time="0.004" classname="com.selenium.testNG.FactoryExample"/>
  <testcase name="c" time="0.006" classname="com.selenium.testNG.FactoryExample"/>
  <testcase name="c" time="0.002" classname="com.selenium.testNG.FactoryExample"/>
</testsuite> <!-- Default test -->
